/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DishTVRechargeLead {
  'id' : bigint,
  'status' : string,
  'paymentScreenshotFile' : [] | [ExternalBlob],
  'operator' : string,
  'createdAt' : bigint,
  'customerId' : string,
  'amount' : string,
}
export type ExternalBlob = Uint8Array;
export interface MobileRechargeLead {
  'id' : bigint,
  'status' : string,
  'paymentScreenshotFile' : [] | [ExternalBlob],
  'operator' : string,
  'createdAt' : bigint,
  'mobileNumber' : string,
  'amount' : string,
}
export interface PaymentBankServiceRequest {
  'id' : bigint,
  'status' : string,
  'createdAt' : bigint,
  'mobileNumber' : string,
  'notes' : string,
  'serviceOption' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WifiBookingLead {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'serviceType' : string,
  'paymentScreenshotFile' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'mobileNumber' : string,
  'aadhaarBackFile' : [] | [ExternalBlob],
  'fullAddress' : string,
  'aadhaarFrontFile' : [] | [ExternalBlob],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllDishTVRechargeLeads' : ActorMethod<[], Array<DishTVRechargeLead>>,
  'getAllMobileRechargeLeads' : ActorMethod<[], Array<MobileRechargeLead>>,
  'getAllPaymentBankServiceRequests' : ActorMethod<
    [],
    Array<PaymentBankServiceRequest>
  >,
  /**
   * / Admin-only: Get all leads
   */
  'getAllWifiBookingLeads' : ActorMethod<[], Array<WifiBookingLead>>,
  'getApprovedMobileRechargeLeads' : ActorMethod<[], Array<MobileRechargeLead>>,
  'getApprovedWifiBookingLeads' : ActorMethod<[], Array<WifiBookingLead>>,
  /**
   * / User Profile Management
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingMobileRechargeLeads' : ActorMethod<[], Array<MobileRechargeLead>>,
  /**
   * / Admin-only: Query functions for status specific leads
   */
  'getPendingWifiBookingLeads' : ActorMethod<[], Array<WifiBookingLead>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDishTVRechargeLead' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    bigint
  >,
  'submitMobileRechargeLead' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    bigint
  >,
  'submitPaymentBankServiceRequest' : ActorMethod<
    [string, string, string],
    bigint
  >,
  /**
   * / Create new lead - Public, no auth required for customers to submit
   */
  'submitWifiBookingLead' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      [] | [ExternalBlob],
    ],
    bigint
  >,
  'updateDishTVRechargeLeadStatus' : ActorMethod<[bigint, string], undefined>,
  'updateMobileRechargeLeadStatus' : ActorMethod<[bigint, string], undefined>,
  'updatePaymentBankServiceRequestStatus' : ActorMethod<
    [bigint, string],
    undefined
  >,
  /**
   * / Admin-only: Update lead status
   */
  'updateWifiBookingLeadStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];