/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DishTVRechargeLead = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'paymentScreenshotFile' : IDL.Opt(ExternalBlob),
  'operator' : IDL.Text,
  'createdAt' : IDL.Int,
  'customerId' : IDL.Text,
  'amount' : IDL.Text,
});
export const MobileRechargeLead = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'paymentScreenshotFile' : IDL.Opt(ExternalBlob),
  'operator' : IDL.Text,
  'createdAt' : IDL.Int,
  'mobileNumber' : IDL.Text,
  'amount' : IDL.Text,
});
export const PaymentBankServiceRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'mobileNumber' : IDL.Text,
  'notes' : IDL.Text,
  'serviceOption' : IDL.Text,
});
export const WifiBookingLead = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'serviceType' : IDL.Text,
  'paymentScreenshotFile' : IDL.Opt(ExternalBlob),
  'createdAt' : IDL.Int,
  'mobileNumber' : IDL.Text,
  'aadhaarBackFile' : IDL.Opt(ExternalBlob),
  'fullAddress' : IDL.Text,
  'latitude' : IDL.Opt(IDL.Text),
  'longitude' : IDL.Opt(IDL.Text),
  'googleMapsLink' : IDL.Opt(IDL.Text),
  'aadhaarFrontFile' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDishTVRechargeLeads' : IDL.Func(
      [],
      [IDL.Vec(DishTVRechargeLead)],
      ['query'],
    ),
  'getAllMobileRechargeLeads' : IDL.Func(
      [],
      [IDL.Vec(MobileRechargeLead)],
      ['query'],
    ),
  'getAllPaymentBankServiceRequests' : IDL.Func(
      [],
      [IDL.Vec(PaymentBankServiceRequest)],
      ['query'],
    ),
  'getAllWifiBookingLeads' : IDL.Func(
      [],
      [IDL.Vec(WifiBookingLead)],
      ['query'],
    ),
  'getDishRechargesWithPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DishTVRechargeLead)],
      ['query'],
    ),
  'getMobileRechargesWithPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MobileRechargeLead)],
      ['query'],
    ),
  'getPaymentBankRequestsWithPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaymentBankServiceRequest)],
      ['query'],
    ),
  'getWifiBookingsWithPassword' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WifiBookingLead)],
      ['query'],
    ),
  'setupAdminDirectly' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getApprovedMobileRechargeLeads' : IDL.Func(
      [],
      [IDL.Vec(MobileRechargeLead)],
      ['query'],
    ),
  'getApprovedWifiBookingLeads' : IDL.Func(
      [],
      [IDL.Vec(WifiBookingLead)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingMobileRechargeLeads' : IDL.Func(
      [],
      [IDL.Vec(MobileRechargeLead)],
      ['query'],
    ),
  'getPendingWifiBookingLeads' : IDL.Func(
      [],
      [IDL.Vec(WifiBookingLead)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDishTVRechargeLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'submitMobileRechargeLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'submitPaymentBankServiceRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitWifiBookingLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'updateDishTVRechargeLeadStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateMobileRechargeLeadStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updatePaymentBankServiceRequestStatus' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateWifiBookingLeadStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DishTVRechargeLead = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'paymentScreenshotFile' : IDL.Opt(ExternalBlob),
    'operator' : IDL.Text,
    'createdAt' : IDL.Int,
    'customerId' : IDL.Text,
    'amount' : IDL.Text,
  });
  const MobileRechargeLead = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'paymentScreenshotFile' : IDL.Opt(ExternalBlob),
    'operator' : IDL.Text,
    'createdAt' : IDL.Int,
    'mobileNumber' : IDL.Text,
    'amount' : IDL.Text,
  });
  const PaymentBankServiceRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'mobileNumber' : IDL.Text,
    'notes' : IDL.Text,
    'serviceOption' : IDL.Text,
  });
  const WifiBookingLead = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'serviceType' : IDL.Text,
    'paymentScreenshotFile' : IDL.Opt(ExternalBlob),
    'createdAt' : IDL.Int,
    'mobileNumber' : IDL.Text,
    'aadhaarBackFile' : IDL.Opt(ExternalBlob),
    'fullAddress' : IDL.Text,
    'latitude' : IDL.Opt(IDL.Text),
    'longitude' : IDL.Opt(IDL.Text),
    'googleMapsLink' : IDL.Opt(IDL.Text),
    'aadhaarFrontFile' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDishTVRechargeLeads' : IDL.Func(
        [],
        [IDL.Vec(DishTVRechargeLead)],
        ['query'],
      ),
    'getAllMobileRechargeLeads' : IDL.Func(
        [],
        [IDL.Vec(MobileRechargeLead)],
        ['query'],
      ),
    'getAllPaymentBankServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(PaymentBankServiceRequest)],
        ['query'],
      ),
    'getAllWifiBookingLeads' : IDL.Func(
        [],
        [IDL.Vec(WifiBookingLead)],
        ['query'],
      ),
    'getDishRechargesWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DishTVRechargeLead)],
        ['query'],
      ),
    'getMobileRechargesWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MobileRechargeLead)],
        ['query'],
      ),
    'getPaymentBankRequestsWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaymentBankServiceRequest)],
        ['query'],
      ),
    'getWifiBookingsWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WifiBookingLead)],
        ['query'],
      ),
    'setupAdminDirectly' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getApprovedMobileRechargeLeads' : IDL.Func(
        [],
        [IDL.Vec(MobileRechargeLead)],
        ['query'],
      ),
    'getApprovedWifiBookingLeads' : IDL.Func(
        [],
        [IDL.Vec(WifiBookingLead)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingMobileRechargeLeads' : IDL.Func(
        [],
        [IDL.Vec(MobileRechargeLead)],
        ['query'],
      ),
    'getPendingWifiBookingLeads' : IDL.Func(
        [],
        [IDL.Vec(WifiBookingLead)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDishTVRechargeLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'submitMobileRechargeLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'submitPaymentBankServiceRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitWifiBookingLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'updateDishTVRechargeLeadStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateMobileRechargeLeadStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updatePaymentBankServiceRequestStatus' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateWifiBookingLeadStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
